### ISSUE TITLE
[bug]:playwrighttimeout

### ISSUE THREAD

**Issue by shi-yingyingjiang** [HibiKier/nonebot-plugin-zxreport#2]
```python
10-18 15:12:25 [SUCCESS] nonebot | OneBot V11 1479785753 | [message.group.normal]: Message 875986741 from 2798134864@[群:375180847] '真寻日报'
10-18 15:12:25 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_zxreport, lineno=29)
10-18 15:12:34 [SUCCESS] nonebot | OneBot V11 1479785753 | [notice.notify.poke]: {'time': 1729235554, 'self_id': 1479785753, 'post_type': 'notice', 'notice_type': 'notify', 'sub_type': 'poke', 'user_id': 1411185175, 'group_id': 375180847, 'target_id': 2798134864, 'suffix': '', 'action_img_url': 'http://tianquan.gtimg.cn/nudgeaction/item/8/expression.jpg', 'action': '揉了揉'}
10-18 15:12:34 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=nonebot_plugin_auto_bot_selector.target, lineno=17)
10-18 15:12:34 [INFO] nonebot | Matcher(type='notice', module=nonebot_plugin_auto_bot_selector.target, lineno=17) running complete
10-18 15:12:34 [INFO] nonebot | Event will be handled by Matcher(type='notice', module=nonebot_plugin_blacklist, lineno=420)
10-18 15:12:34 [INFO] nonebot | Matcher(type='notice', module=nonebot_plugin_blacklist, lineno=420) running complete
10-18 15:12:38 [SUCCESS] nonebot | OneBot V11 1479785753 | [message.group.normal]: Message 1029200792 from 1215354209@[ 群:791704225] '端起碗骂娘了'
10-18 15:12:39 [SUCCESS] nonebot | OneBot V11 1479785753 | [message.group.normal]: Message 876084791 from 1411185175@[群:375180847] '撅[at:qq=2798134864,name=@是、熒熒酱] '
10-18 15:12:40 [INFO] nonebot | Event will be handled by AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=163)
10-18 15:12:42 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_memes.matchers.command, lineno=163) running complete
10-18 15:12:49 [SUCCESS] nonebot | OneBot V11 1479785753 | [message.group.normal]: Message 876193836 from 1411185175@[群:375180847] '透[at:qq=2798134864,name=@是、熒熒酱] '
10-18 15:12:51 [SUCCESS] nonebot | OneBot V11 1479785753 | [message.group.normal]: Message 1029256952 from 2630038258@[ 群:791704225] '[mface:url=https://gxh.vip.qq.com/club/item/parcel/item/eb/ebee9d9c1ac50257a93...,emoji_package_id=238251,emoji_id=ebee9d9c1ac50257a93b47ca4f4f697c,key=634be7390652cd14,summary=[给你一拳]][给你一拳]'
10-18 15:12:54 [SUCCESS] nonebot | OneBot V11 1479785753 | [message.group.normal]: Message 1029321052 from 2630038258@[ 群:791704225] '[mface:url=https://gxh.vip.qq.com/club/item/parcel/item/6d/6de62c6328e8ee17951...,emoji_package_id=238251,emoji_id=6de62c6328e8ee179514ce42d3cd4654,key=634be7390652cd14,summary=[似啊]][似啊]'
10-18 15:13:03 [INFO] nonebot | AlconnaMatcher(type='', module=nonebot_plugin_zxreport, lineno=29) running complete
10-18 15:13:03 [ERROR] nonebot | Running AlconnaMatcher(type='', module=nonebot_plugin_zxreport, lineno=29) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\bot.py", line 67, in <module>
    nonebot.run()
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\drivers\fastapi.py", line 186, in run
    uvicorn.run(
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\uvicorn\main.py", line 577, in run
    server.run()
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 628, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 595, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1881, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\internal\matcher\matcher.py", line 825, in simple_run
    await handler(
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot\dependencies\__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot_plugin_zxreport\__init__.py", line 34, in _
    path = await Report.get_report_image()
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot_plugin_zxreport\data_source.py", line 74, in get_report_image
    image_bytes = await template_to_pic(
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot_plugin_htmlrender\data_source.py", line 259, in template_to_pic
    return await html_to_pic(
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\nonebot_plugin_htmlrender\data_source.py", line 205, in html_to_pic
    await page.set_content(html, wait_until="networkidle")
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\playwright\async_api\_generated.py", line 9185, in set_content
    await self._impl_obj.set_content(
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\playwright\_impl\_page.py", line 464, in set_content
    return await self._main_frame.set_content(**locals_to_params(locals()))
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\playwright\_impl\_frame.py", line 417, in set_content
    await self._channel.send("setContent", locals_to_params(locals()))
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\playwright\_impl\_connection.py", line 490, in wrap_api_call
    return await cb()
  File "C:\Users\Administrator\Downloads\nb2-fast-deploy-main\.venv\lib\site-packages\playwright\_impl\_connection.py", line 99, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
setting frame content, waiting until "networkidle"
============================================================
```

**Comment by cy1159178778** [comment]
echarts.min.js在线加载有时候有点慢，改成本地引入就不会超时了

**Comment by HibiKier** [comment]
d8ed029915a20999da7256b926615241580392f2
